### ISSUE TITLE
After installing Chinese CorelDRAW 2020, I can't see the tools.

### ISSUE THREAD

**Issue by hongwenjun** [fersatgit/SmartDepart#1]
After installing Chinese CorelDRAW 2020, I can't see the tools.

Is there a C language version? Assembly language is a mystery and I can't understand it.

C:\Program Files\Corel\CorelDRAW Graphics Suite 2020\Programs64\Addons\SmartDepart

![11](https://github.com/fersatgit/SmartDepart/assets/1762909/1a97b916-1894-4b8d-a80b-74f857cf71cb)

**Comment by fersatgit** [comment]
To show plugin icon you need to reset property panel to it defaults. Icon only shows when "combine (Ctrl+L)" icon shows. So plugin don`t works with text (need convert text to curves before use).

**Comment by fersatgit** [comment]
I have mixed Delphi7/FASM 32-bit debug code compilable as exe. Polygon-intersection routine and curve to polyline converter in FASM, rest of code in Delphi.

**Comment by hongwenjun** [comment]
![QQ图片20240615125037](https://github.com/fersatgit/SmartDepart/assets/1762909/9f811509-8b92-4572-a221-b1bc25c96121)

Thank you for your reply. I tried it in CorelDRAW 2020 but it still didn't work. I guess the reason is:
CorelDRAW 2020 and X7 UI libraries have changed, and the API has changed.
Because I learned C/C++ to build CPG yesterday, CorelDRAW X6 64bit worked fine, but the command button built in CorelDRAW 2020 was wrong and could not be used.

VGCore::CommandBarControlPtr ctl ...;
The CommandBarControlPtr class has changed in CDR2020

**Comment by fersatgit** [comment]
You are not one, who tells me about it difference in corel versions. Recently I have wrote a little tool, and it also don`t work in 2020 - https://www.cyberforum.ru/coreldraw/thread3169753.html. But it work fine in X7, 2018, 2024.

I see you use SetCustomIcon - this method don`t work since 17 version of corel. In newer versions you must use SetIcon2 instead - this method accept only ico files.

**Comment by fersatgit** [comment]
Also in my recearch i found interesting feature of old versions CorelDraw - it possible to include icon as base64 code immideately in xslt. But this feature no longer supported.

**Comment by fersatgit** [comment]
Here another example in delphi - https://forum.rudtp.ru/attachments/cpg-example-7z.164729/. This 32-bit cpg should work in x3 and higher. It installs in "Draw\Plugins" dirrectory (if dirrecory not exists - just create it).

**Comment by hongwenjun** [comment]
![GIF](https://github.com/fersatgit/SmartDepart/assets/1762909/a8b2d3db-f21d-44c6-a466-b339111abc78)

https://github.com/hongwenjun/CorelDRAW-CPG/tree/main/03_ClearFill

03_ClearFill in my CPG learning project was compiled with the SDK of CorelDRAW 2020. It runs correctly under CorelDRAW X6, but fails under CorelDRAW 2020. There is a difference between the high and low versions, which is a real headache.

```
STDMETHODIMP CVGAppPlugin::raw_StartSession()
{
  try
  {
    m_pApp->AddPluginCommand(_bstr_t("ClearFill"), _bstr_t("Clear Fill"), _bstr_t("Clears fill from selected objects"));

    // CorelDRAW X6 使用 VGCore::CommandBarControlPtr ctl
    // CorelDRAW 2020 使用  VGCore::ICUIControlPtr ctl，能通过编译，不过运行目前有错误
    VGCore::ICUIControlPtr ctl = m_pApp->CommandBars->Item[_bstr_t("CorelVBA")]->Controls->AddCustomButton(VGCore::cdrCmdCategoryPlugins, _bstr_t("ClearFill"), 0, VARIANT_TRUE);
//    _bstr_t bstrPath(m_pApp->Path + _bstr_t("Plugins64\\ClearFill.bmp"));
    ctl->SetIcon2(_bstr_t("guid://d2fdc0d9-09f8-4948-944c-4297395c05b7"));
    m_lCookie = m_pApp->AdviseEvents(this);
  }
  catch(_com_error &e)
  {
    MessageBox(NULL, e.Description(), _T("Error"), MB_ICONSTOP);
  }
  return S_OK;
}
```

![Errot](https://github.com/fersatgit/SmartDepart/assets/1762909/d06a1f27-3bfc-47fb-ae26-b5d6817ee199)

**Comment by hongwenjun** [comment]
![123](https://github.com/fersatgit/SmartDepart/assets/1762909/2f9ce069-246c-49f0-9b6b-9a721a0c310d)

Locate the error of CorelDRAW 2020 CPG creating button icons,
Comment out the code for creating button icons, and then test using the same function code in VBA,
Create a button for CPG plug-in to use, and it can call "clear fill color" normally

```
Sub Macro1()
    With CommandBars.Item("Test")
      .Visible = True
      Set ctl = .Controls.AddCustomButton(cdrCmdCategoryPlugins, "ClearFill")
      ctl.SetIcon2 ("guid://a8e62a7a-d5d2-4a05-8d5d-e07d6bd21993")
    End With
End Sub

```

**Comment by fersatgit** [comment]
Code  from [ToastyСut](https://github.com/fersatgit/ToastyCut/blob/main/ToastyCut.asm)

`cominvk Controls,AddCustomButton,cdrCmdCategoryMacros,strMacroName,1,0,Control`

As you see "index" is 1 (in your code its 0) and "temporary" is false (in your code its true). As I remember that parameters may result to crash Corel with some "incorrect" values. I picked that values in many tryes.

**Comment by hongwenjun** [comment]
Thank you, Master. The button icon added in CorelDRAW 2020 can be used normally. I hope your tool can also be repaired and used normally.

**Comment by fersatgit** [comment]
I have checked work in Corel 2020 both x86 and x64 versions - it`s all right.
![1](https://github.com/fersatgit/SmartDepart/assets/122711455/cd0ba6dc-ecc7-4aa6-a9f5-e597a377a888)

**Comment by fersatgit** [comment]
I have checked work in Corel 2020 both x86 and x64 versions - it`s all right.
![1](https://github.com/fersatgit/SmartDepart/assets/122711455/4d56cbe1-d7f7-4dfd-8777-52f01d859d52)

**Comment by hongwenjun** [comment]
![QQ截图20240828101511](https://github.com/user-attachments/assets/d67d1d40-8ddb-484e-a272-7b6dfac47377)

IVGApplicationPtr app(L"CorelDRAW.Application.22"); // The version I installed before could not bind to Windows COM, probably because of this.
## I installed a new version today, which can bind to Windows COM normally, so I can use your plug-in.

## Annoying things: Today, CDR2020 cannot use VBA GMS plug-in under Windows Chinese system:
![22](https://github.com/user-attachments/assets/0db0ed90-bcc0-4200-800b-e0527f5519f0)

##  Last night I wrote some interesting code for curve intersection:
https://git.lyvba.com/hongwenjun/cdrapp/src/master/cdrapp.cpp
```
bool isDPCurve(IVGShapePtr s) {
  auto dpc = (s->Type == cdrRectangleShape) || (s->Type == cdrEllipseShape) ||
             (s->Type == cdrCurveShape) || (s->Type == cdrPolygonShape) ||
             (s->Type == cdrBitmapShape);
  return dpc;
}
IVGShapePtr CreateBoundary(corel *cdr, IVGShapePtr s) {
  //  auto scp = s2->CreateBoundary(0, 0 , true, true);
  //  This is only supported by API X7 and above, so now just draw a rectangle
  BoundingBox box;
  s->GET_BOUNDING_BOX(box);
  auto scp =
      cdr->ActiveLayer->CreateRectangle2(box.x, box.y, box.w, box.h, ZERO_4PC);
  return scp;
}
// VGCore::IVGShapePtr VGCore::IVGShape::CreateBoundary ( double x, double y,
// VARIANT_BOOL PlaceOnTop, VARIANT_BOOL DeleteSource ); VGCore::IVGShapePtr
// VGCore::IVGShapeRange::CreateBoundary ( double x, double y, VARIANT_BOOL
// PlaceOnTop, VARIANT_BOOL DeleteSource ); VARIANT_BOOL
// VGCore::IVGCurve::IntersectsWith ( struct IVGCurve * Curve )
void test_IntersectsWith(corel *cdr) {

  auto sr = cdr->ActiveSelectionRange;
  if (1 < sr->Count) {
    bool isIn = false;

    auto s1 = sr->Shapes->Item[1];
    auto s2 = sr->Shapes->Item[2];

    if (isDPCurve(s1) && isDPCurve(s2)) {
      isIn = s1->GetDisplayCurve()->IntersectsWith(s2->GetDisplayCurve());
    } else if (isDPCurve(s1)) {
      // Group text and other types such as OLE to create a temporary boundary range
      auto scp = CreateBoundary(cdr, s2);
      isIn = s1->GetDisplayCurve()->IntersectsWith(scp->GetDisplayCurve());
      scp->Delete();

    } else if (isDPCurve(s2)) {
      auto scp = CreateBoundary(cdr, s1);
      isIn = scp->GetDisplayCurve()->IntersectsWith(s2->GetDisplayCurve());
      scp->Delete();
    } else {
      auto scp = CreateBoundary(cdr, s1);
      auto scp2 = CreateBoundary(cdr, s2);
      isIn = scp->GetDisplayCurve()->IntersectsWith(scp2->GetDisplayCurve());
      scp->Delete();
      scp2->Delete();
    }

    if (isIn)
      Test_Intersect(cdr);   // Another interesting code
  }
}
```

**Comment by fersatgit** [comment]
Seems I finally understand why button not appear. It happens if your current workspace is different to default. To fix this just put copy of AppUI.xslt in SmartDepart directory and rename it to UserUI.xslt.

>CDR2020 cannot use VBA GMS plug-in under Windows Chinese system:

Seems CorelDraw haven`t permissions to write in "R:\". Try yo run CorelDraw from administrator.

>The version I installed before could not bind to Windows COM,

CPG-plugin recieve IVGApplication interface directly. COM not needed.
